### ISSUE TITLE
Can't Enable VSCode Animations (Sorry for not labeling, new to this github issue thing)

### ISSUE THREAD

**Issue by LonelyDude** [BrandonKirbyson/VSCode-Animations#20]
The extension seems enabled, tried everything in Troubleshoot but still couldn't get it running (though the cursor animation works fine for some reason), version of the extension is 1.0.12, version of Custom CSS and JS is 7.2.1

**Comment by BrandonKirbyson** [comment]
What OS are you trying this on?

**Comment by LonelyDude** [comment]
> What OS are you trying this on?

Windows 10 Pro

**Comment by BrandonKirbyson** [comment]
Ok, there were previous issues with windows due to this extension requiring vscode to be run as administrator for the custom css to apply, is this how you are running it?

**Comment by LonelyDude** [comment]
> Ok, there were previous issues with windows due to this extension requiring vscode to be run as administrator for the custom css to apply, is this how you are running it?

I have updated the extension (which by the way could only be installed manually for me, not sure if I should) and ran it as administrator, but it still didn't work

**Comment by BrandonKirbyson** [comment]
Ok, sorry but I can't really debug on windows. I'm betting your problem is that the custom css and js is not properly being added to vscode. We can check that if you follow these steps:

- Make sure you launched vscode as an administrator and you have all the default settings for the extension, can be found running command: `Animations: Open Animation Settings` or searching `animations` in settings
- Run the `Animations: Install Animations` command in vscode and then click `Install`, vscode should reload when you click that
- Wait like 5 seconds and then test by making a split screen or opening command palette (top command searching bar) to check if it works, if it does then your good! Otherwise, continue
- If nothing happened yet, continue and run the command `Developer: Toggle Developer Tools`
- Go to the console tab in developer tools, then where it has an input saying filter paste: `VSCode-Animations`

![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/86384607/297be119-b843-4a5e-83f4-ccf27555586f)

Let me know if you see `VSCode-Animations: Successfully Installed!` or if you have any questions about this process. If that is not logged then your issue is likely with the dependency extension [Custom CSS and JS](https://github.com/be5invis/vscode-custom-css) and not running the extension/vscode as administrator. I can still help just that extension might have more info about this issue.

**Comment by BrandonKirbyson** [comment]
Did you get it to work @LonelyDude?

**Comment by mbalc** [comment]
I have a similar issue on Windows 11 @BrandonKirbyson (although on my very first installation, I saw it work actually for a moment, but after I restarted my vscode cause I had to configure some other thing, it ceased to work and no amount of uninstalls/reinstalls fixes the issue

I tried your script from earlier; I don't get the "Successfully Installed" message, I get these two guys instead:
![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/11033790/e09147dd-cbe0-4a7f-a639-f23e938b63dd)

**Comment by BrandonKirbyson** [comment]
Ok, thank you for including the logs, they are likely this extension. It's odd why that wouldn't be the case for way more people and that is more an issue with [Custom CSS and JS](https://github.com/be5invis/vscode-custom-css) but I can look into fixing it.

Currently I am working on a new version of the extension that gives an option to use another injection extension instead of [Custom CSS and JS](https://github.com/be5invis/vscode-custom-css) since the new one [Apc Customize UI++](https://github.com/drcika/apc-extension) apparently works better on windows. This might not be published for a little bit but I'll let you know when it is and hopefully the other extension will work better but if not then I will look more into fixing it.

**Comment by Gero670** [comment]
Same problem here, I'd love to use this, the previews are awesome!
I'm on windows 11 and don't know if it makes an actual difference but I'm on VSCodium

**Comment by BrandonKirbyson** [comment]
Published the new version for vscode, still need to publish to vscodium

**Comment by BrandonKirbyson** [comment]
Now published to vscodium! I tested it out myself (vscodium on mac) and it worked so hopefully it will work for you, let me know how it goes.

**Comment by mbalc** [comment]
just updated the extension, so far everything seems to work great

**Comment by BrandonKirbyson** [comment]
Ok great, I'll close this issue it everything works for @Gero670 also.

**Comment by BrandonKirbyson** [comment]
Great!

**Comment by MrRobot-k** [comment]
> What OS are you trying this on?

Kali Linux
