### ISSUE TITLE
Allow to use custom injector instead of "Custom CSS and JS Loader"

### ISSUE THREAD

**Issue by AlexOwl** [BrandonKirbyson/VSCode-Animations#21]
There are some other injector extensions available which are used for other projects. I dont like the idea to use multiple injection types, because it will likely broke in a couple of updates. I use [apc](https://github.com/drcika/apc-extension) (apc.imports setting) which provides customisation of UI and completely makes sense to use with your animations. It doesnt spawn message about corrupted visual studio and loads your extension without any problem. 

First of all, "Custom CSS and JS Loader" method didnt work for me also 
And I would like to uninstall that extension, but VS throws an error "Cannot uninstall 'Custom CSS and JS Loader' extension. 'VSCode Animations' extension depends on this"
I can't remove "vscode_custom_css.imports" setting either, every reload it adds your updateHandler.js

Anyway, thanks for your great job!

**Comment by BrandonKirbyson** [comment]
Ok, good idea. I am not too sure about removing the custom css and js as a dependency since it allows people to easily get it set up but what do you think about if I made a toggle setting for automatic using custom css and js or custom? Custom CSS and JS doesn't do anything if you leave it disabled anyways, I know this isn't the best if you really don't like that extension but for other people that want a quick install it should stay a dependency.

Let me know if that setting would be good. I could also make a command you can run to get the url of the file to paste into your settings and of course it wouldn't automatically add it to the custom css and js ones if you turned that setting on.

The main reason I wouldn't convert entirely to another injection extension is because it would be a mess for everyone who currently has the extension.

**Comment by AlexOwl** [comment]
Yep, the setting toggle would be great

**Comment by BrandonKirbyson** [comment]
Published `1.0.14` which adds this. Check the [new section on the readme for info](https://github.com/BrandonKirbyson/VSCode-Animations#for-other-custom-injection-extension-or-open-vsx). Let me know if everything works properly sometime and then I will close this issue.

**Comment by BrandonKirbyson** [comment]
I am going to assume it works for you and close this now.

**Comment by AlexOwl** [comment]
@BrandonKirbyson thanks, it works like a charm
