### ISSUE TITLE
Side pane slide animation not working with images or jupyter notebooks

### ISSUE THREAD

**Issue by EgeCaliskan** [BrandonKirbyson/VSCode-Animations#34]
Everything works normally and the animations play out as they are supposed to, but whenever I open up a jupyter notebook or an image the side panel sliding doesn't work. It just dissapears when I hit ctrl + b instead of sliding to the side. I also noticed that smooth scrolling option in VS Code's own settings doesn't work with notebooks, but I'm not sure if this is related to the problem.

**Comment by BrandonKirbyson** [comment]
Ok, I might look into this soon but currently animations partially disable when an iframe (jupyter notebook uses iframes and image likely too) is detected because vscode manually calculates iframe sizing so it does not animate properly and previously when I tried it ended up breaking iframes entirely (making them odd widths).

**Comment by MrT-tak** [comment]
Hi, I just reinstalled vscod eand got vscode animations to work.

**Comment by MrT-tak** [comment]
Hi
I just reinstalled vscode and got vscode animations working.
I don't know if it because I have soo many items in one folder but the slide animations is not working.
Is there any possible reasons for this?
Thanks!

**Comment by MrT-tak** [comment]
> Hi I just reinstalled vscode and got vscode animations working. I don't know if it because I have soo many items in one folder but the slide animations is not working. Is there any possible reasons for this? Thanks!

nvm it worked after a restart
