### ISSUE TITLE
Warning after installation

### ISSUE THREAD

**Issue by PraetorP** [BrandonKirbyson/VSCode-Animations#5]
I got message "Your Code installation appears to be corrupt. Please reinstall"
![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/45266194/e88acc09-326b-4fa0-b5de-451a818c27ec)
Also toolbars resizing leads to freezes of the interface.
https://github.com/BrandonKirbyson/VSCode-Animations/assets/45266194/d5f87c89-26da-49e2-871c-81370228dcb0

**Comment by BrandonKirbyson** [comment]
The notification is because I have to embed custom css and js into vscode's UI, there isn't actually any issue but vscode will throw an error. Just click the settings icon and "do not show again". 
The toolbar freezing is something I can't control but I could make the smooth mode no affect views when resizing, do you think that would be a good option?

**Comment by PraetorP** [comment]
First of all, I would like to thank you for this extension.
>The notification is because I have to embed custom css and js into vscode's UI, there isn't actually any issue but vscode will throw an error. Just click the settings icon and "do not show again".
I didn't notice any mention of this in the extension's description, so I thought it was abnormal behavior, so I thought I'd let you know.
>The toolbar freezing is something I can't control but I could make the smooth mode not affect views when resizing, do you think that would be a good option?
Yes, I agree with you (that this would be a good one). Perhaps lighter (in terms of rendering) effects are needed (as an alternative). IMHO in its current state it degrades the user experience.
