### ISSUE TITLE
Secondary Side Bar Redraws Too Often

### ISSUE THREAD

**Issue by davegi** [BrandonKirbyson/VSCode-Animations#57]
I keep the Outline view opened in the Secondary Side Bar on the left edge of Code. Every selection in the editor window causes the Outline to be redrawn. Very distracting. Any thoughts? Thx.

**Comment by BrandonKirbyson** [comment]
That is likely because of the scrolling animation. I can look into fixing it but that way this works it might not be possible to fix stuff like that. If you don't care too much about the scrolling animation could you try disabling that? Also, I could possibly just disable that animation in the outline.

**Comment by BrandonKirbyson** [comment]
Fixed in the new version `2.0.2`.
