### ISSUE TITLE
Hide sidebar more gracefully

### ISSUE THREAD

**Issue by Jaeiya** [BrandonKirbyson/VSCode-Animations#6]
When opening the side bar it animates nicely into view, however when hiding the sidebar, it instantly closes, but the code editor slides back to center of screen as if the sidebar is still sliding out of view. It would be nice to have the sidebar slide-out as nicely as it slides in.

That being said, amazing work!👍 

**Side-note:** In your demo video, what VSCode theme are you using?

**Comment by BrandonKirbyson** [comment]
Of course, I get to that soon. Thanks for the feedback.

The theme is [Solarized Palenight](https://marketplace.visualstudio.com/items?itemName=BrandonKirbyson.solarized-palenight&ssr=false#overview)

**Comment by BrandonKirbyson** [comment]
Same as #8 a closing animation would not properly work with the way the vscode editor is setup because it would get messy and buggy even adding a simple closing animation because the elements would have to be caught before deletion. Same as #8, maybe in the future or if anyone has ideas on this I will add closing animations but for now I think it is better to not.
